#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

if [[ $l =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	pin -c 5 "sl"
echo
	"Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
